# Generated by Django 5.1.4 on 2024-12-14 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_customer_address_customer_bio_customer_dob_and_more'),
        ('farmers', '0002_farmer_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='farmer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='farmers.farmer'),
            preserve_default=False,
        ),
    ]
