# Generated by Django 5.1.4 on 2024-12-14 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_order_farmer'),
        ('farmers', '0002_farmer_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.product'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
