# Generated by Django 5.1.4 on 2024-12-14 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_alter_order_product_delete_product'),
        ('farmers', '0003_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='farmers.product'),
            preserve_default=False,
        ),
    ]
