# Generated by Django 5.1.4 on 2024-12-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
